---
- name: Include OS and distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
      skip: true

- name: Set architecture
  set_fact:
    goquorum_architecture: "darwin"
  when: ansible_os_family == "Darwin"

- name: Install goquorum
  include_tasks: "install.yml"
#
#- name: Run OS specific installation tasks
#  include_tasks: "{{ item }}"
#  with_first_found:
#    - files:
#        - "{{ ansible_distribution|lower }}/install.yml"
#        - "{{ ansible_os_family|lower }}/install.yml"
#      skip: true

- name: Get IP address to bind to if not provided
  include_tasks: "network.yml"
  when: not goquorum_host_ip

- name: Create config
  include_tasks: "config.yml"

#- name: Create goquorum service
#  include_tasks: "service.yml"
