---
- name: Create goquorum systemd service
  template:
    src: "{{ goquorum_systemd_template }}"
    dest: "{{ goquorum_systemd_dir }}/goquorum.service"
    owner: "root"
    group: "root"
  become: true
  when: ( goquorum_managed_service ) and
    ( ansible_os_family != "Darwin" )
  register: systemd_file

- name: Set updated optionally to trigger a systemd restart at the end
  set_fact:
    goquorum_state_updates: "{{ goquorum_state_updates + ['goquorum.systemd_file'] }}"
  when: systemd_file is changed

- name: Reload systemd to reread configs
  systemd:
    daemon_reload: yes
  become: true
  when: systemd_file is changed

- name: Enable and start goquorum service
  systemd:
    name: goquorum
    state: "{{ goquorum_systemd_state }}"
    enabled: true
  become: true
  when: ( goquorum_state_updates|length > 0 ) and
    ( goquorum_managed_service ) and
    ( ansible_os_family != "Darwin" )

